// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pbuf/dcft.proto

package com.logicmonitor.research.dcft.message;

public final class MW {
  private MW() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DcftHeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.logicmonitor.research.dcft.message.DcftHeartbeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 cliId = 1;</code>
     */
    boolean hasCliId();
    /**
     * <code>required int32 cliId = 1;</code>
     */
    int getCliId();

    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    boolean hasMembershipListVersion();
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    long getMembershipListVersion();
  }
  /**
   * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftHeartbeat}
   */
  public static final class DcftHeartbeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.logicmonitor.research.dcft.message.DcftHeartbeat)
      DcftHeartbeatOrBuilder {
    // Use DcftHeartbeat.newBuilder() to construct.
    private DcftHeartbeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DcftHeartbeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DcftHeartbeat defaultInstance;
    public static DcftHeartbeat getDefaultInstance() {
      return defaultInstance;
    }

    public DcftHeartbeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DcftHeartbeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cliId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              membershipListVersion_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.class, com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder.class);
    }

    public static com.google.protobuf.Parser<DcftHeartbeat> PARSER =
        new com.google.protobuf.AbstractParser<DcftHeartbeat>() {
      public DcftHeartbeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DcftHeartbeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DcftHeartbeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLIID_FIELD_NUMBER = 1;
    private int cliId_;
    /**
     * <code>required int32 cliId = 1;</code>
     */
    public boolean hasCliId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cliId = 1;</code>
     */
    public int getCliId() {
      return cliId_;
    }

    public static final int MEMBERSHIPLISTVERSION_FIELD_NUMBER = 2;
    private long membershipListVersion_;
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    public boolean hasMembershipListVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    public long getMembershipListVersion() {
      return membershipListVersion_;
    }

    private void initFields() {
      cliId_ = 0;
      membershipListVersion_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCliId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMembershipListVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cliId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, membershipListVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cliId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, membershipListVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicmonitor.research.dcft.message.MW.DcftHeartbeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftHeartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.logicmonitor.research.dcft.message.DcftHeartbeat)
        com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.class, com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder.class);
      }

      // Construct using com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cliId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        membershipListVersion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat getDefaultInstanceForType() {
        return com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance();
      }

      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat build() {
        com.logicmonitor.research.dcft.message.MW.DcftHeartbeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat buildPartial() {
        com.logicmonitor.research.dcft.message.MW.DcftHeartbeat result = new com.logicmonitor.research.dcft.message.MW.DcftHeartbeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cliId_ = cliId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.membershipListVersion_ = membershipListVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicmonitor.research.dcft.message.MW.DcftHeartbeat) {
          return mergeFrom((com.logicmonitor.research.dcft.message.MW.DcftHeartbeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicmonitor.research.dcft.message.MW.DcftHeartbeat other) {
        if (other == com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance()) return this;
        if (other.hasCliId()) {
          setCliId(other.getCliId());
        }
        if (other.hasMembershipListVersion()) {
          setMembershipListVersion(other.getMembershipListVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCliId()) {
          
          return false;
        }
        if (!hasMembershipListVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicmonitor.research.dcft.message.MW.DcftHeartbeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicmonitor.research.dcft.message.MW.DcftHeartbeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cliId_ ;
      /**
       * <code>required int32 cliId = 1;</code>
       */
      public boolean hasCliId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cliId = 1;</code>
       */
      public int getCliId() {
        return cliId_;
      }
      /**
       * <code>required int32 cliId = 1;</code>
       */
      public Builder setCliId(int value) {
        bitField0_ |= 0x00000001;
        cliId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cliId = 1;</code>
       */
      public Builder clearCliId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cliId_ = 0;
        onChanged();
        return this;
      }

      private long membershipListVersion_ ;
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public boolean hasMembershipListVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public long getMembershipListVersion() {
        return membershipListVersion_;
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public Builder setMembershipListVersion(long value) {
        bitField0_ |= 0x00000002;
        membershipListVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public Builder clearMembershipListVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        membershipListVersion_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.logicmonitor.research.dcft.message.DcftHeartbeat)
    }

    static {
      defaultInstance = new DcftHeartbeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.logicmonitor.research.dcft.message.DcftHeartbeat)
  }

  public interface DcftMembershipListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.logicmonitor.research.dcft.message.DcftMembershipList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 txnId = 1;</code>
     */
    boolean hasTxnId();
    /**
     * <code>required int64 txnId = 1;</code>
     */
    long getTxnId();

    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    boolean hasMembershipListVersion();
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    long getMembershipListVersion();

    /**
     * <code>repeated int32 members = 3;</code>
     */
    java.util.List<java.lang.Integer> getMembersList();
    /**
     * <code>repeated int32 members = 3;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated int32 members = 3;</code>
     */
    int getMembers(int index);
  }
  /**
   * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMembershipList}
   */
  public static final class DcftMembershipList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.logicmonitor.research.dcft.message.DcftMembershipList)
      DcftMembershipListOrBuilder {
    // Use DcftMembershipList.newBuilder() to construct.
    private DcftMembershipList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DcftMembershipList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DcftMembershipList defaultInstance;
    public static DcftMembershipList getDefaultInstance() {
      return defaultInstance;
    }

    public DcftMembershipList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DcftMembershipList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              txnId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              membershipListVersion_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                members_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              members_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                members_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                members_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = java.util.Collections.unmodifiableList(members_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicmonitor.research.dcft.message.MW.DcftMembershipList.class, com.logicmonitor.research.dcft.message.MW.DcftMembershipList.Builder.class);
    }

    public static com.google.protobuf.Parser<DcftMembershipList> PARSER =
        new com.google.protobuf.AbstractParser<DcftMembershipList>() {
      public DcftMembershipList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DcftMembershipList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DcftMembershipList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TXNID_FIELD_NUMBER = 1;
    private long txnId_;
    /**
     * <code>required int64 txnId = 1;</code>
     */
    public boolean hasTxnId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 txnId = 1;</code>
     */
    public long getTxnId() {
      return txnId_;
    }

    public static final int MEMBERSHIPLISTVERSION_FIELD_NUMBER = 2;
    private long membershipListVersion_;
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    public boolean hasMembershipListVersion() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 membershipListVersion = 2;</code>
     */
    public long getMembershipListVersion() {
      return membershipListVersion_;
    }

    public static final int MEMBERS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> members_;
    /**
     * <code>repeated int32 members = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated int32 members = 3;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated int32 members = 3;</code>
     */
    public int getMembers(int index) {
      return members_.get(index);
    }

    private void initFields() {
      txnId_ = 0L;
      membershipListVersion_ = 0L;
      members_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTxnId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMembershipListVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, txnId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, membershipListVersion_);
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeInt32(3, members_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, txnId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, membershipListVersion_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(members_.get(i));
        }
        size += dataSize;
        size += 1 * getMembersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicmonitor.research.dcft.message.MW.DcftMembershipList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMembershipList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.logicmonitor.research.dcft.message.DcftMembershipList)
        com.logicmonitor.research.dcft.message.MW.DcftMembershipListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicmonitor.research.dcft.message.MW.DcftMembershipList.class, com.logicmonitor.research.dcft.message.MW.DcftMembershipList.Builder.class);
      }

      // Construct using com.logicmonitor.research.dcft.message.MW.DcftMembershipList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        txnId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        membershipListVersion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipList getDefaultInstanceForType() {
        return com.logicmonitor.research.dcft.message.MW.DcftMembershipList.getDefaultInstance();
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipList build() {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipList buildPartial() {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipList result = new com.logicmonitor.research.dcft.message.MW.DcftMembershipList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txnId_ = txnId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.membershipListVersion_ = membershipListVersion_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.members_ = members_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicmonitor.research.dcft.message.MW.DcftMembershipList) {
          return mergeFrom((com.logicmonitor.research.dcft.message.MW.DcftMembershipList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicmonitor.research.dcft.message.MW.DcftMembershipList other) {
        if (other == com.logicmonitor.research.dcft.message.MW.DcftMembershipList.getDefaultInstance()) return this;
        if (other.hasTxnId()) {
          setTxnId(other.getTxnId());
        }
        if (other.hasMembershipListVersion()) {
          setMembershipListVersion(other.getMembershipListVersion());
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTxnId()) {
          
          return false;
        }
        if (!hasMembershipListVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicmonitor.research.dcft.message.MW.DcftMembershipList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long txnId_ ;
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public boolean hasTxnId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public long getTxnId() {
        return txnId_;
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public Builder setTxnId(long value) {
        bitField0_ |= 0x00000001;
        txnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public Builder clearTxnId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        txnId_ = 0L;
        onChanged();
        return this;
      }

      private long membershipListVersion_ ;
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public boolean hasMembershipListVersion() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public long getMembershipListVersion() {
        return membershipListVersion_;
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public Builder setMembershipListVersion(long value) {
        bitField0_ |= 0x00000002;
        membershipListVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 membershipListVersion = 2;</code>
       */
      public Builder clearMembershipListVersion() {
        bitField0_ = (bitField0_ & ~0x00000002);
        membershipListVersion_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> members_ = java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          members_ = new java.util.ArrayList<java.lang.Integer>(members_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getMembersList() {
        return java.util.Collections.unmodifiableList(members_);
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public int getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public Builder setMembers(
          int index, int value) {
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public Builder addMembers(int value) {
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public Builder addAllMembers(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 members = 3;</code>
       */
      public Builder clearMembers() {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.logicmonitor.research.dcft.message.DcftMembershipList)
    }

    static {
      defaultInstance = new DcftMembershipList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.logicmonitor.research.dcft.message.DcftMembershipList)
  }

  public interface DcftMembershipListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.logicmonitor.research.dcft.message.DcftMembershipListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 txnId = 1;</code>
     */
    boolean hasTxnId();
    /**
     * <code>required int64 txnId = 1;</code>
     */
    long getTxnId();

    /**
     * <code>required int32 cliId = 2;</code>
     */
    boolean hasCliId();
    /**
     * <code>required int32 cliId = 2;</code>
     */
    int getCliId();

    /**
     * <code>required int64 membershipListVersion = 3;</code>
     */
    boolean hasMembershipListVersion();
    /**
     * <code>required int64 membershipListVersion = 3;</code>
     */
    long getMembershipListVersion();
  }
  /**
   * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMembershipListResponse}
   */
  public static final class DcftMembershipListResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.logicmonitor.research.dcft.message.DcftMembershipListResponse)
      DcftMembershipListResponseOrBuilder {
    // Use DcftMembershipListResponse.newBuilder() to construct.
    private DcftMembershipListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DcftMembershipListResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DcftMembershipListResponse defaultInstance;
    public static DcftMembershipListResponse getDefaultInstance() {
      return defaultInstance;
    }

    public DcftMembershipListResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DcftMembershipListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              txnId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cliId_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              membershipListVersion_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.class, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<DcftMembershipListResponse> PARSER =
        new com.google.protobuf.AbstractParser<DcftMembershipListResponse>() {
      public DcftMembershipListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DcftMembershipListResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DcftMembershipListResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TXNID_FIELD_NUMBER = 1;
    private long txnId_;
    /**
     * <code>required int64 txnId = 1;</code>
     */
    public boolean hasTxnId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 txnId = 1;</code>
     */
    public long getTxnId() {
      return txnId_;
    }

    public static final int CLIID_FIELD_NUMBER = 2;
    private int cliId_;
    /**
     * <code>required int32 cliId = 2;</code>
     */
    public boolean hasCliId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cliId = 2;</code>
     */
    public int getCliId() {
      return cliId_;
    }

    public static final int MEMBERSHIPLISTVERSION_FIELD_NUMBER = 3;
    private long membershipListVersion_;
    /**
     * <code>required int64 membershipListVersion = 3;</code>
     */
    public boolean hasMembershipListVersion() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 membershipListVersion = 3;</code>
     */
    public long getMembershipListVersion() {
      return membershipListVersion_;
    }

    private void initFields() {
      txnId_ = 0L;
      cliId_ = 0;
      membershipListVersion_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTxnId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCliId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMembershipListVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, txnId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cliId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, membershipListVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, txnId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cliId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, membershipListVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMembershipListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.logicmonitor.research.dcft.message.DcftMembershipListResponse)
        com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.class, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder.class);
      }

      // Construct using com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        txnId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        cliId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        membershipListVersion_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse getDefaultInstanceForType() {
        return com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance();
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse build() {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse buildPartial() {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse result = new com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.txnId_ = txnId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cliId_ = cliId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.membershipListVersion_ = membershipListVersion_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse) {
          return mergeFrom((com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse other) {
        if (other == com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance()) return this;
        if (other.hasTxnId()) {
          setTxnId(other.getTxnId());
        }
        if (other.hasCliId()) {
          setCliId(other.getCliId());
        }
        if (other.hasMembershipListVersion()) {
          setMembershipListVersion(other.getMembershipListVersion());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTxnId()) {
          
          return false;
        }
        if (!hasCliId()) {
          
          return false;
        }
        if (!hasMembershipListVersion()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long txnId_ ;
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public boolean hasTxnId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public long getTxnId() {
        return txnId_;
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public Builder setTxnId(long value) {
        bitField0_ |= 0x00000001;
        txnId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 txnId = 1;</code>
       */
      public Builder clearTxnId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        txnId_ = 0L;
        onChanged();
        return this;
      }

      private int cliId_ ;
      /**
       * <code>required int32 cliId = 2;</code>
       */
      public boolean hasCliId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cliId = 2;</code>
       */
      public int getCliId() {
        return cliId_;
      }
      /**
       * <code>required int32 cliId = 2;</code>
       */
      public Builder setCliId(int value) {
        bitField0_ |= 0x00000002;
        cliId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cliId = 2;</code>
       */
      public Builder clearCliId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cliId_ = 0;
        onChanged();
        return this;
      }

      private long membershipListVersion_ ;
      /**
       * <code>required int64 membershipListVersion = 3;</code>
       */
      public boolean hasMembershipListVersion() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 membershipListVersion = 3;</code>
       */
      public long getMembershipListVersion() {
        return membershipListVersion_;
      }
      /**
       * <code>required int64 membershipListVersion = 3;</code>
       */
      public Builder setMembershipListVersion(long value) {
        bitField0_ |= 0x00000004;
        membershipListVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 membershipListVersion = 3;</code>
       */
      public Builder clearMembershipListVersion() {
        bitField0_ = (bitField0_ & ~0x00000004);
        membershipListVersion_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.logicmonitor.research.dcft.message.DcftMembershipListResponse)
    }

    static {
      defaultInstance = new DcftMembershipListResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.logicmonitor.research.dcft.message.DcftMembershipListResponse)
  }

  public interface DcftMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.logicmonitor.research.dcft.message.DcftMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    com.logicmonitor.research.dcft.message.MW.DcftHeartbeat getHeartbeat();
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    boolean hasMembershipResponse();
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse getMembershipResponse();
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder getMembershipResponseOrBuilder();
  }
  /**
   * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMessage}
   */
  public static final class DcftMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.logicmonitor.research.dcft.message.DcftMessage)
      DcftMessageOrBuilder {
    // Use DcftMessage.newBuilder() to construct.
    private DcftMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DcftMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DcftMessage defaultInstance;
    public static DcftMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DcftMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DcftMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = heartbeat_.toBuilder();
              }
              heartbeat_ = input.readMessage(com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heartbeat_);
                heartbeat_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = membershipResponse_.toBuilder();
              }
              membershipResponse_ = input.readMessage(com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(membershipResponse_);
                membershipResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.logicmonitor.research.dcft.message.MW.DcftMessage.class, com.logicmonitor.research.dcft.message.MW.DcftMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DcftMessage> PARSER =
        new com.google.protobuf.AbstractParser<DcftMessage>() {
      public DcftMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DcftMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DcftMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEARTBEAT_FIELD_NUMBER = 1;
    private com.logicmonitor.research.dcft.message.MW.DcftHeartbeat heartbeat_;
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    public boolean hasHeartbeat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat getHeartbeat() {
      return heartbeat_;
    }
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
     */
    public com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder getHeartbeatOrBuilder() {
      return heartbeat_;
    }

    public static final int MEMBERSHIPRESPONSE_FIELD_NUMBER = 2;
    private com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse membershipResponse_;
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    public boolean hasMembershipResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse getMembershipResponse() {
      return membershipResponse_;
    }
    /**
     * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
     */
    public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder getMembershipResponseOrBuilder() {
      return membershipResponse_;
    }

    private void initFields() {
      heartbeat_ = com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance();
      membershipResponse_ = com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMembershipResponse()) {
        if (!getMembershipResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, membershipResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, heartbeat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, membershipResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.logicmonitor.research.dcft.message.MW.DcftMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.logicmonitor.research.dcft.message.MW.DcftMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.logicmonitor.research.dcft.message.DcftMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.logicmonitor.research.dcft.message.DcftMessage)
        com.logicmonitor.research.dcft.message.MW.DcftMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.logicmonitor.research.dcft.message.MW.DcftMessage.class, com.logicmonitor.research.dcft.message.MW.DcftMessage.Builder.class);
      }

      // Construct using com.logicmonitor.research.dcft.message.MW.DcftMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeartbeatFieldBuilder();
          getMembershipResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (heartbeatBuilder_ == null) {
          heartbeat_ = com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (membershipResponseBuilder_ == null) {
          membershipResponse_ = com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance();
        } else {
          membershipResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.logicmonitor.research.dcft.message.MW.internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMessage getDefaultInstanceForType() {
        return com.logicmonitor.research.dcft.message.MW.DcftMessage.getDefaultInstance();
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMessage build() {
        com.logicmonitor.research.dcft.message.MW.DcftMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.logicmonitor.research.dcft.message.MW.DcftMessage buildPartial() {
        com.logicmonitor.research.dcft.message.MW.DcftMessage result = new com.logicmonitor.research.dcft.message.MW.DcftMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (heartbeatBuilder_ == null) {
          result.heartbeat_ = heartbeat_;
        } else {
          result.heartbeat_ = heartbeatBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (membershipResponseBuilder_ == null) {
          result.membershipResponse_ = membershipResponse_;
        } else {
          result.membershipResponse_ = membershipResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.logicmonitor.research.dcft.message.MW.DcftMessage) {
          return mergeFrom((com.logicmonitor.research.dcft.message.MW.DcftMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.logicmonitor.research.dcft.message.MW.DcftMessage other) {
        if (other == com.logicmonitor.research.dcft.message.MW.DcftMessage.getDefaultInstance()) return this;
        if (other.hasHeartbeat()) {
          mergeHeartbeat(other.getHeartbeat());
        }
        if (other.hasMembershipResponse()) {
          mergeMembershipResponse(other.getMembershipResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        if (hasMembershipResponse()) {
          if (!getMembershipResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.logicmonitor.research.dcft.message.MW.DcftMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.logicmonitor.research.dcft.message.MW.DcftMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.logicmonitor.research.dcft.message.MW.DcftHeartbeat heartbeat_ = com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.logicmonitor.research.dcft.message.MW.DcftHeartbeat, com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder, com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public boolean hasHeartbeat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          return heartbeat_;
        } else {
          return heartbeatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public Builder setHeartbeat(com.logicmonitor.research.dcft.message.MW.DcftHeartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heartbeat_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public Builder setHeartbeat(
          com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public Builder mergeHeartbeat(com.logicmonitor.research.dcft.message.MW.DcftHeartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              heartbeat_ != com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance()) {
            heartbeat_ =
              com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.newBuilder(heartbeat_).mergeFrom(value).buildPartial();
          } else {
            heartbeat_ = value;
          }
          onChanged();
        } else {
          heartbeatBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          heartbeat_ = com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.getDefaultInstance();
          onChanged();
        } else {
          heartbeatBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder getHeartbeatBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder getHeartbeatOrBuilder() {
        if (heartbeatBuilder_ != null) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          return heartbeat_;
        }
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftHeartbeat heartbeat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.logicmonitor.research.dcft.message.MW.DcftHeartbeat, com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder, com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.logicmonitor.research.dcft.message.MW.DcftHeartbeat, com.logicmonitor.research.dcft.message.MW.DcftHeartbeat.Builder, com.logicmonitor.research.dcft.message.MW.DcftHeartbeatOrBuilder>(
                  getHeartbeat(),
                  getParentForChildren(),
                  isClean());
          heartbeat_ = null;
        }
        return heartbeatBuilder_;
      }

      private com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse membershipResponse_ = com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder> membershipResponseBuilder_;
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public boolean hasMembershipResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse getMembershipResponse() {
        if (membershipResponseBuilder_ == null) {
          return membershipResponse_;
        } else {
          return membershipResponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public Builder setMembershipResponse(com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse value) {
        if (membershipResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          membershipResponse_ = value;
          onChanged();
        } else {
          membershipResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public Builder setMembershipResponse(
          com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder builderForValue) {
        if (membershipResponseBuilder_ == null) {
          membershipResponse_ = builderForValue.build();
          onChanged();
        } else {
          membershipResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public Builder mergeMembershipResponse(com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse value) {
        if (membershipResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              membershipResponse_ != com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance()) {
            membershipResponse_ =
              com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.newBuilder(membershipResponse_).mergeFrom(value).buildPartial();
          } else {
            membershipResponse_ = value;
          }
          onChanged();
        } else {
          membershipResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public Builder clearMembershipResponse() {
        if (membershipResponseBuilder_ == null) {
          membershipResponse_ = com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.getDefaultInstance();
          onChanged();
        } else {
          membershipResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder getMembershipResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMembershipResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      public com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder getMembershipResponseOrBuilder() {
        if (membershipResponseBuilder_ != null) {
          return membershipResponseBuilder_.getMessageOrBuilder();
        } else {
          return membershipResponse_;
        }
      }
      /**
       * <code>optional .com.logicmonitor.research.dcft.message.DcftMembershipListResponse membershipResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder> 
          getMembershipResponseFieldBuilder() {
        if (membershipResponseBuilder_ == null) {
          membershipResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponse.Builder, com.logicmonitor.research.dcft.message.MW.DcftMembershipListResponseOrBuilder>(
                  getMembershipResponse(),
                  getParentForChildren(),
                  isClean());
          membershipResponse_ = null;
        }
        return membershipResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.logicmonitor.research.dcft.message.DcftMessage)
    }

    static {
      defaultInstance = new DcftMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.logicmonitor.research.dcft.message.DcftMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_logicmonitor_research_dcft_message_DcftMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017pbuf/dcft.proto\022&com.logicmonitor.rese" +
      "arch.dcft.message\"=\n\rDcftHeartbeat\022\r\n\005cl" +
      "iId\030\001 \002(\005\022\035\n\025membershipListVersion\030\002 \002(\003" +
      "\"S\n\022DcftMembershipList\022\r\n\005txnId\030\001 \002(\003\022\035\n" +
      "\025membershipListVersion\030\002 \002(\003\022\017\n\007members\030" +
      "\003 \003(\005\"Y\n\032DcftMembershipListResponse\022\r\n\005t" +
      "xnId\030\001 \002(\003\022\r\n\005cliId\030\002 \002(\005\022\035\n\025membershipL" +
      "istVersion\030\003 \002(\003\"\267\001\n\013DcftMessage\022H\n\thear" +
      "tbeat\030\001 \001(\01325.com.logicmonitor.research." +
      "dcft.message.DcftHeartbeat\022^\n\022membership",
      "Response\030\002 \001(\0132B.com.logicmonitor.resear" +
      "ch.dcft.message.DcftMembershipListRespon" +
      "seB,\n&com.logicmonitor.research.dcft.mes" +
      "sageB\002MW"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_logicmonitor_research_dcft_message_DcftHeartbeat_descriptor,
        new java.lang.String[] { "CliId", "MembershipListVersion", });
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_logicmonitor_research_dcft_message_DcftMembershipList_descriptor,
        new java.lang.String[] { "TxnId", "MembershipListVersion", "Members", });
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_logicmonitor_research_dcft_message_DcftMembershipListResponse_descriptor,
        new java.lang.String[] { "TxnId", "CliId", "MembershipListVersion", });
    internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_logicmonitor_research_dcft_message_DcftMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_logicmonitor_research_dcft_message_DcftMessage_descriptor,
        new java.lang.String[] { "Heartbeat", "MembershipResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
